name: Deploy
on: workflow_dispatch
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: Install dependencies
        run: npm ci --force
      - name: Check
        run: npm run check
      - name: Deploy to Netlify
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          SPOONACULAR_KEY: ${{ secrets.SPOONACULAR_KEY }}
          NEXT_PUBLIC_SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
        run: |
          npx ntl deploy --prod \
            --dir build \
            --site snapfridge \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
